-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Hakutarkoitus CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS JulkinenProfiilisivu CASCADE;
DROP TABLE IF EXISTS SalainenSivu CASCADE;
DROP TABLE IF EXISTS Kiinnostukset CASCADE;
DROP TABLE IF EXISTS Kohteet CASCADE;
DROP TABLE IF EXISTS Viesti CASCADE;
DROP TABLE IF EXISTS Vastaanottaja CASCADE;
